--
-- PostgreSQL database dump
--

\restrict O3UUqgYE3vtbnteXRrVFciGbeXnbMwMSweQJn6Z6f1sMmG8SflTqkCMjex9ZsO2

-- Dumped from database version 17.7 (Ubuntu 17.7-3.pgdg24.04+1)
-- Dumped by pg_dump version 17.7 (Ubuntu 17.7-3.pgdg24.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

-- *not* creating schema, since initdb creates it


SET default_tablespace = '';

SET default_table_access_method = "heap";

--
-- Name: activation_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE "public"."activation_tokens" (
    "id" bigint NOT NULL,
    "created_at" timestamp(6) with time zone,
    "expires_at" timestamp(6) with time zone,
    "token" character varying(100) NOT NULL,
    "user_id" bigint NOT NULL
);


--
-- Name: activation_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE "public"."activation_tokens" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."activation_tokens_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: captcha_data; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE "public"."captcha_data" (
    "id" bigint NOT NULL,
    "created_at" bigint,
    "data" character varying(255),
    "expires_at" bigint,
    "parameters" character varying(255),
    "request_id" "uuid" NOT NULL,
    "solution" character varying(255),
    "status" character varying(255),
    "type" character varying(255),
    "user_ip" character varying(255),
    CONSTRAINT "captcha_data_status_check" CHECK ((("status")::"text" = ANY ((ARRAY['CREATED'::character varying, 'SOLVED'::character varying, 'EXPIRED'::character varying, 'FAILED'::character varying])::"text"[]))),
    CONSTRAINT "captcha_data_type_check" CHECK ((("type")::"text" = ANY ((ARRAY['CLICK_IN_ORDER'::character varying, 'SELECT_ALL'::character varying])::"text"[])))
);


--
-- Name: captcha_data_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE "public"."captcha_data" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."captcha_data_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: consumer_api_keys; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE "public"."consumer_api_keys" (
    "id" "uuid" NOT NULL,
    "api_key_hash" character varying(255),
    "api_key_version" character varying(255),
    "domain_url" character varying(255),
    "label" character varying(255),
    "name" character varying(255),
    "revoked" boolean NOT NULL,
    "user_id" bigint NOT NULL
);


--
-- Name: pass_recovery_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE "public"."pass_recovery_tokens" (
    "id" bigint NOT NULL,
    "created_at" timestamp(6) with time zone,
    "expires_at" timestamp(6) with time zone,
    "token" character varying(100) NOT NULL,
    "user_id" bigint NOT NULL
);


--
-- Name: pass_recovery_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE "public"."pass_recovery_tokens" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."pass_recovery_tokens_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_limits; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE "public"."user_limits" (
    "id" bigint NOT NULL,
    "daily_captcha_limit" integer,
    "hourly_captcha_limit" integer,
    "user_id" bigint
);


--
-- Name: user_limits_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE "public"."user_limits" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."user_limits_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE "public"."users" (
    "id" bigint NOT NULL,
    "email" character varying(255),
    "enabled" boolean NOT NULL,
    "password" character varying(255),
    "role" character varying(255),
    "username" character varying(255)
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE "public"."users" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."users_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: activation_tokens activation_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY "public"."activation_tokens"
    ADD CONSTRAINT "activation_tokens_pkey" PRIMARY KEY ("id");


--
-- Name: captcha_data captcha_data_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY "public"."captcha_data"
    ADD CONSTRAINT "captcha_data_pkey" PRIMARY KEY ("id");


--
-- Name: consumer_api_keys consumer_api_keys_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY "public"."consumer_api_keys"
    ADD CONSTRAINT "consumer_api_keys_pkey" PRIMARY KEY ("id");


--
-- Name: pass_recovery_tokens pass_recovery_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY "public"."pass_recovery_tokens"
    ADD CONSTRAINT "pass_recovery_tokens_pkey" PRIMARY KEY ("id");


--
-- Name: user_limits uk1qr0x11bsxion8yoaog2mrbx6; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY "public"."user_limits"
    ADD CONSTRAINT "uk1qr0x11bsxion8yoaog2mrbx6" UNIQUE ("user_id");


--
-- Name: activation_tokens uk5jny0xpou62bqdjhkbw1c0qxd; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY "public"."activation_tokens"
    ADD CONSTRAINT "uk5jny0xpou62bqdjhkbw1c0qxd" UNIQUE ("token");


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "uk6dotkott2kjsp8vw4d0m25fb7" UNIQUE ("email");


--
-- Name: pass_recovery_tokens ukibc8l0tediekocjjd21hgoy9o; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY "public"."pass_recovery_tokens"
    ADD CONSTRAINT "ukibc8l0tediekocjjd21hgoy9o" UNIQUE ("token");


--
-- Name: captcha_data ukk838tuedsw4frgxk7sxfwd047; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY "public"."captcha_data"
    ADD CONSTRAINT "ukk838tuedsw4frgxk7sxfwd047" UNIQUE ("request_id");


--
-- Name: users ukr43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "ukr43af9ap4edm43mmtq01oddj6" UNIQUE ("username");


--
-- Name: user_limits user_limits_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY "public"."user_limits"
    ADD CONSTRAINT "user_limits_pkey" PRIMARY KEY ("id");


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_pkey" PRIMARY KEY ("id");


--
-- Name: idx_at_expires_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "idx_at_expires_at" ON "public"."activation_tokens" USING "btree" ("expires_at");


--
-- Name: idx_at_token; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "idx_at_token" ON "public"."activation_tokens" USING "btree" ("token");


--
-- Name: idx_at_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "idx_at_user_id" ON "public"."activation_tokens" USING "btree" ("user_id");


--
-- Name: idx_consumer_api_key_hash; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "idx_consumer_api_key_hash" ON "public"."consumer_api_keys" USING "btree" ("api_key_hash");


--
-- Name: idx_consumer_api_key_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "idx_consumer_api_key_user_id" ON "public"."consumer_api_keys" USING "btree" ("user_id");


--
-- Name: idx_prt_expires_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "idx_prt_expires_at" ON "public"."pass_recovery_tokens" USING "btree" ("expires_at");


--
-- Name: idx_prt_token; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "idx_prt_token" ON "public"."pass_recovery_tokens" USING "btree" ("token");


--
-- Name: idx_prt_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "idx_prt_user_id" ON "public"."pass_recovery_tokens" USING "btree" ("user_id");


--
-- Name: idx_user_email; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "idx_user_email" ON "public"."users" USING "btree" ("email");


--
-- Name: idx_user_limits_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "idx_user_limits_user_id" ON "public"."user_limits" USING "btree" ("user_id");


--
-- Name: idx_user_username; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "idx_user_username" ON "public"."users" USING "btree" ("username");


--
-- Name: pass_recovery_tokens fk4djuixwedeku4lo0n0co7akww; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY "public"."pass_recovery_tokens"
    ADD CONSTRAINT "fk4djuixwedeku4lo0n0co7akww" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id");


--
-- Name: consumer_api_keys fkeipc8tte53ios51d5v1uudtua; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY "public"."consumer_api_keys"
    ADD CONSTRAINT "fkeipc8tte53ios51d5v1uudtua" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id");


--
-- Name: activation_tokens fkgtry5rof27b5hdur1a11y0gsn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY "public"."activation_tokens"
    ADD CONSTRAINT "fkgtry5rof27b5hdur1a11y0gsn" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id");


--
-- Name: user_limits fkh4b3llbo5yu7mhe2gwgvlhl0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY "public"."user_limits"
    ADD CONSTRAINT "fkh4b3llbo5yu7mhe2gwgvlhl0" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id");


--
-- PostgreSQL database dump complete
--

\unrestrict O3UUqgYE3vtbnteXRrVFciGbeXnbMwMSweQJn6Z6f1sMmG8SflTqkCMjex9ZsO2

